version: '3.8'

services:
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "5555:5555"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=classpath:/config/,file:/config/
    volumes:
      - ./config-repo:/config
      - ./logs/config-service:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5555/actuator/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 60s
    networks:
      - microservices-net
    stop_grace_period: 30s

  eureka-server:
    build: ./eureka-discoveryservice
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:5555
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - microservices-net
    volumes:
      - ./logs/eureka-discovery:/app/logs
    stop_grace_period: 30s

  gateway-service:
    build: ./gatewayservice
    container_name: gateway-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - microservices-net
    volumes:
      - ./logs/gateway-service:/app/logs
    stop_grace_period: 30s

  authentificationservice:
    build: ./authentificationservice
    container_name: authentification-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:users-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_H2_CONSOLE_ENABLED=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=authentification-service
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8089/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - ./logs/authentificationservice:/app/logs
    stop_grace_period: 30s
    
  client-service:
    build: ./client-service
    container_name: client-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:client-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_H2_CONSOLE_ENABLED=true
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - microservices-net
    volumes:
      - ./logs/client-service:/app/logs
    stop_grace_period: 30s

  produit-service:
    build: ./produit-service
    container_name: produit-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:produit-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_H2_CONSOLE_ENABLED=true
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - microservices-net
    volumes:
      - ./logs/produit-service:/app/logs
    stop_grace_period: 30s

  factureservice:
    build: ./factureservice
    container_name: facture-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:facture-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_H2_CONSOLE_ENABLED=true
      - EUREKA_INSTANCE_INSTANCE_ID=$${spring.application.name}:$${random.value}
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - microservices-net
    volumes:
      - ./logs/facture-service:/app/logs
    stop_grace_period: 30s

  reglement-service:
    build: ./reglement-service
    container_name: reglement-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:reglement-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_H2_CONSOLE_ENABLED=true
      - EUREKA_INSTANCE_INSTANCE_ID=$${spring.application.name}:$${random.value}
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8084/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - microservices-net
    volumes:
      - ./logs/reglement-service:/app/logs
    stop_grace_period: 30s

  devise-service:
    build: ./devise-service
    container_name: devise-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:devise-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_H2_CONSOLE_ENABLED=true
      - EUREKA_INSTANCE_INSTANCE_ID=$${spring.application.name}:$${random.value}
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - microservices-net
    volumes:
      - ./logs/devise-service:/app/logs
    stop_grace_period: 30s

networks:
  microservices-net:
    driver: bridge